; PIC12F675 Configuration Bit Settings

; Assembly source line config statements

#include "p12f675.inc"

; CONFIG
; __config 0x3185
 __CONFIG _FOSC_INTRCCLK & _WDTE_OFF & _PWRTE_ON & _MCLRE_OFF & _BOREN_OFF & _CP_OFF & _CPD_OFF
 
; PAGINAÇÃO DE MEMORIA
 
 #DEFINE	BANK0	BCF STATUS,RP0	    ;BANCO 0 DE MEMÓRIA
 #DEFINE	BANK1	BSF STATUS,RP0	    ;BANCO 1 DE MEMORIA
 
; CONSTANTES
 
 ; VARIÁVEIS
 
   CBLOCK   0X20			    ;INICIO MEMÓRIA - REGISTRADORES DE USO GERAL 

   ENDC					    ;FIM DA ALOCAÇÃO DE REGISTRADORES DE USO GERAL
   
 ; SAÍDAS
 
 #DEFINE	LED	GPIO,0		    ;SAÍDA LED 1 NA PORTA 0
 #DEFINE	BTN	GPIO,2		    ;BOTÃO DE INTERRUPÇÃO EXTERNA
 
 ; VETOR RESET
 
    ORG	    0X00			    ;
    GOTO    SETUP			    ;CONFIGURAÇÃO INICIAL DOS REGISTRADORES
    
; VETOR DE INTERRUPÇÃO    
    ORG	    0X04
    
    BTFSC   INTCON,1			    ;TESTA T0IF, PULA SE = A ZERO   
    BSF	    LED
;    MOVLW   B'00000001'			    ;MASCARA P/ INVERSÃO DOS PINOS
;    XORWF   GPIO,F			    ;OU EXCLUSIVO, COMPARA E INVERTE OS PINOS 0 E 2
    
    RETFIE				    ;RETORNA DE INTERRUPÇÃO
    
SETUP:    
        
    BANK1				    ;MOVE P/ O BANCO 1 DE MEMORIA
    
    MOVLW   0X00
    MOVWF   ANSEL			    ;DESABILITA I/O ANALÓGICO			    ;
    
    MOVLW   B'11111110'			    ;
    MOVWF   TRISIO			    ;CONFIG PORTAS 
        
    MOVLW   B'11000000'			    ;
    MOVWF   OPTION_REG			    ;CONFIGURA O PRESCALER DO TMR0 (1:4)
    
    MOVLW   B'10010000'			    ;
    MOVWF   INTCON			    ;HABILITA A INT EXTERNA NA INTCON
    
    MOVLW   B'00000000'			    ;
    MOVWF   ANSEL			    ;DESLIGA ENTRADAS ANALOGICAS
    
    BANK0				    ;VOLTA P/ O BANCO 0
    MOVLW   B'00000111'			    ;
    MOVWF   CMCON			    ;DESLIGA OS COMPARADORES
    BCF	    LED
 
    
; ROTINA PRINCIPAL    
    
MAIN:

    
    GOTO    MAIN

    
    END
   
 



