; PIC12F675 Configuration Bit Settings

; Assembly source line config statements

#include "p12f675.inc"

; CONFIG
; __config 0x3185
 __CONFIG _FOSC_INTRCCLK & _WDTE_OFF & _PWRTE_ON & _MCLRE_OFF & _BOREN_OFF & _CP_OFF & _CPD_OFF
 
; PAGINAÇÃO DE MEMORIA
 
 #DEFINE	BANK0	BCF STATUS,RP0	    ;BANCO 0 DE MEMÓRIA
 #DEFINE	BANK1	BSF STATUS,RP0	    ;BANCO 1 DE MEMORIA
 
; CONSTANTES
 #DEFINE	TEMPO	D'005'		    ;FLAG DO TMR0
 
 ; VARIÁVEIS
 
   CBLOCK   0X20			    ;INICIO MEMÓRIA - REGISTRADORES DE USO GERAL 

   ENDC					    ;FIM DA ALOCAÇÃO DE REGISTRADORES DE USO GERAL
   
 ; SAÍDAS
 
 #DEFINE	LED1	GPIO,2		    ;SAÍDA LED 1 NA PORTA 4
 #DEFINE	LED2	GPIO,0		    ;SAIDA LED 2 NA PORTA 2
 
 ; VETOR RESET
 
    ORG	    0X00			    ;
    GOTO    SETUP			    ;CONFIGURAÇÃO INICIAL DOS REGISTRADORES
    
; VETOR DE INTERRUPÇÃO    
    ORG	    0X04
    
    BTFSC   PIR1,0			    ;TESTA T1IF, PULA SE = A ZERO   
    CALL    INVERTE			    ;CHAMA A FUNÇÃO INVERTE
    
    RETFIE				    ;RETORNA DE INTERRUPÇÃO
    
SETUP:    
    MOVLW   B'00111001'			    ;
    MOVWF   T1CON			    ;CONFIG REGISTRADOR DO TMR1
    
    BANK1				    ;MOVE P/ O BANCO 1 DE MEMORIA
    
    MOVLW   0X00
    MOVWF   ANSEL			    ;DESABILITA I/O ANALÓGICO			    ;
    
    MOVLW   B'00000000'			    ;
    MOVWF   TRISIO			    ;CONFIG PORTAS 2 E 4 COMO SAIDAS
        
    MOVLW   B'11000000'			    ;
    MOVWF   INTCON			    ;HABILITA AS INTERRUPÇÕES GERAIS
    
    MOVLW   B'00000001'			    ;
    MOVWF   PIE1			    ;CONFIG ESTOURO DO TMR1
    
    BANK0				    ;VOLTA P/ O BANCO 0
    MOVLW   B'00000111'			    ;
    MOVWF   CMCON			    ;DESLIGA OS COMPARADORES
    MOVLW   B'00000001'			    ;
    MOVWF   GPIO			    ;INICIA COM O PINO 0 EM HIGH 
    
; ROTINA PRINCIPAL    
    
MAIN:

    
    GOTO    MAIN

INVERTE:    
    MOVLW   B'00000101'			    ;MASCARA P/ INVERSÃO DOS PINOS
    XORWF   GPIO,F			    ;OU EXCLUSIVO, COMPARA E INVERTE OS PINOS 0 E 2
    BCF	    PIR1,0
    RETURN
    
    END